# name: Scrape and Notify

# on:
#   schedule:
#     # Runs every hour
#     - cron: '0 * * * *'
#   workflow_dispatch: # Allows manual triggering

# jobs:
#   scrape-and-notify:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.9'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run Scrape Script
#       run: python scrapeApple.py

#     - name: Run Notification Script
#       env:
#         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#       run: python notifyApple.py
name: Scrape and Notify

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Download the previous CSV file as an artifact (if exists)
    - name: Download CSV file artifact
      uses: actions/download-artifact@v3
      with:
        name: apple-jobs
        path: .

    # Step 3: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 4: Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Run the scraping script
    - name: Run Scraping Script
      run: python scrapeApple.py

    # Step 6: Run the notification script
    - name: Run Notification Script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python notifyApple.py

    # Step 7: Upload the updated CSV file as an artifact
    - name: Upload CSV file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: apple-jobs
        path: apple_jobs_today.csv
